



final cards = [
  {'card':'Se fosses um animal que animal gostavas de ser ? Porquê?',"url":"images/sefossesanimal.png",'category':'Q'},
  {'card':'Se fosses uma planta, qual serias? Porquê ?',"url":"images/sefossesplanta.png",'category':'Q'},
  {'card':'Expressa um agradecimento por algo que tenhas vivido com alguém deste grupo',"url":"images/agradecimento.png",'category':'P'},
  {'card':'Qual foi a coisa mais louca que fizeste na vida?',"url":"images/coisamaislouca.png",'category':'P'},
  {'card':'Canta ao grupo uma música que usarias para adormecer um bébé. (sem os adormecer)',"url":"images/musicaadormecerbebe.png",'category':'Q'},
  {'card':'Conta ao grupo por gestos como aprendeste a andar de bicicleta',"url":"images/comoaprendestebicicleta.png",'category':'D'},
  {'card':'Conta ao grupo como chegaste aqui hoje. Depois pede ao grupo para contar esta história contigo',"url":"images/comochegasteaquihoje.png",'category':'D'},
  {'card':'Como nasceste?',"url":"images/comonasceste.png",'category':'P'},
  {'card':'Como é que foi o teu brimeiro beijo?',"url":"images/comoprimeirobeijo.png",'category':'D'},
  {'card':'Como te estás a sentir neste momento?',"url":"images/comotesentes.png",'category':'Q'},
  {'card':'Convida alguém do grupo para cantar contigo uma canção de que gostes. Podem improvisar instrumentos.',"url":"images/convidacantarcontigo.png",'category':'D'},
  {'card':'Representa com o teu corpo uma situação em que te sentes bloqueado na tua vida atual',"url":"images/corposituacaobloqueado.png",'category':'P'},
  {'card':'Inventa uma dança com sons. Podes envolver mais pessoas do grupo',"url":"images/dancacomsons.png",'category':'D'},
  {'card':'Faz uma dança em que moves 3 partes do corpo em simultâneo',"url":"images/dancatrespartescorpo.png",'category':'D'},
  {'card':'Imita um animal de que gostes sem revelar qual é',"url":"images/imitaanimal.png",'category':'D'},
  {'card':'Faz uma massagem nos ombros da pessoa que está À tua direita',"url":"images/massagemadireita.png",'category':'Q'},
  {'card':'Convida todo o grupo a fazer uma massagem coletiva.',"url":"images/massagemcoletiva.png",'category':'Q'},
  {'card':'Qual foi o momento mais alegre que viveste nos últimos sete dias?',"url":"images/momentomaisalegre.png",'category':'P'},
  {'card':'Qual foi o momento mais desafiante que viveste nos últimos cinco anos?',"url":"images/momentomaisdesafiante.png",'category':'P'},
  {'card':'Qual foi o momento mais divertido que viveste no último ano?',"url":"images/momentomaisdivertidoano.png",'category':'D'},
  {'card':'Qual foi o momento mais divertido que viveste na última semana?',"url":"images/momentomaisdivertidosemana.png",'category':'D'},
  {'card':'Qual foi o momento + triste que viveste nos últimos 3 meses?',"url":"images/momentomaistriste.png",'category':'P'},
  {'card':'Mostra ao grupo o que guardas na tua carteira.',"url":"images/oqueguardascarteira.png",'category':'Q'},
  {'card':'?',"url":"images/Surprise.png"},
  {'card':'?',"url":"images/Surprise.png"},
  {'card':'O que é que te faz corar?',"url":"images/oquetefazcorar.png",'category':'D'},
  {'card':'O que perguntarias a Deus?',"url":"images/perguntaadeus.png",'category':'P'},
  {'card':'Qual é a pergunta que gostavas que te fizessem?',"url":"images/perguntatefizessem.png",'category':'P'},
  {'card':'Qual é a primeira coisa que fazes ao acordar ?',"url":"images/primeiracoisaacordar.png",'category':'Q'},
  {'card':'Que pergunta gostavas de fazer à pessoa que está à tua frente ? Porquê ?',"url":"images/queperguntapessoafrente.png",'category':'Q'},
  {'card':'Conta ao grupo algo que gostarias de realizar nos próximos 2 anos.',"url":"images/realizarproximosdoisanos.png",'category':'P'},
  {'card':'Se fosses um jornalista, quem gostarias de entrevistar? Porquê ?',"url":"images/sefossesjornalista.png",'category':'Q'},
  {'card':'Se fosses um objeto deste lugar, qual serias? Porquê ?',"url":"images/sefossesobjeto.png",'category':'Q'},
  {'card':'Conta uma situação marcante que viveste com uma pessoa deste grupo.',"url":"images/situacaomarcante.png",'category':'P'},
  {'card':'Tens a tua sobrevivência garantida. Em que te ocupas?',"url":"images/sobrevivenciagarantida.png",'category':'P'},
  {'card':'Quais são os teus três maiores valores ?',"url":"images/tresmaioresvalores.png",'category':'P'},
  {'card':'Alguma vez viste a tua vida andar para trás?',"url":"images/vidaandarparatras.png",'category':'P'},
  {'card':'Partilha um momento em que sentiste raiva. Como agiste?',"url":"images/momentoraiva.png",'category':'P'},
  {'card':'Se fosses um livro, que livro serias? Porquê?','category':'Q'}
];
final cardsQ = [
  {'card':'Se fosses um animal que animal gostavas de ser ? Porquê?',"url":"images/sefossesanimal.png",'category':'Q'},
  {'card':'Se fosses uma planta, qual serias? Porquê ?',"url":"images/sefossesplanta.png",'category':'Q'},
  {'card':'Canta ao grupo uma música que usarias para adormecer um bébé. (sem os adormecer)',"url":"images/musicaadormecerbebe.png",'category':'Q'},
  {'card':'Como te estás a sentir neste momento?',"url":"images/comotesentes.png",'category':'Q'},
  {'card':'Faz uma massagem nos ombros da pessoa que está À tua direita',"url":"images/massagemadireita.png",'category':'Q'},
  {'card':'Convida todo o grupo a fazer uma massagem coletiva.',"url":"images/massagemcoletiva.png",'category':'Q'},
  {'card':'Mostra ao grupo o que guardas na tua carteira.',"url":"images/oqueguardascarteira.png",'category':'Q'},
  {'card':'?',"url":"images/Surprise.png"},
  {'card':'Qual é a primeira coisa que fazes ao acordar ?',"url":"images/primeiracoisaacordar.png",'category':'Q'},
  {'card':'Que pergunta gostavas de fazer à pessoa que está à tua frente ? Porquê ?',"url":"images/queperguntapessoafrente.png",'category':'Q'},
  {'card':'Se fosses um jornalista, quem gostarias de entrevistar? Porquê ?',"url":"images/sefossesjornalista.png",'category':'Q'},
  {'card':'Se fosses um objeto deste lugar, qual serias? Porquê ?',"url":"images/sefossesobjeto.png",'category':'Q'},
  {'card':'Se fosses um livro, que livro serias? Porquê?','category':'Q'}
];
final cardsP = [
  {'card':'Expressa um agradecimento por algo que tenhas vivido com alguém deste grupo',"url":"images/agradecimento.png",'category':'P'},
  {'card':'Qual foi a coisa mais louca que fizeste na vida?',"url":"images/coisamaislouca.png",'category':'P'},
  {'card':'Como nasceste?',"url":"images/comonasceste.png",'category':'P'},
  {'card':'Representa com o teu corpo uma situação em que te sentes bloqueado na tua vida atual',"url":"images/corposituacaobloqueado.png",'category':'P'},
  {'card':'Qual foi o momento mais alegre que viveste nos últimos sete dias?',"url":"images/momentomaisalegre.png",'category':'P'},
  {'card':'Qual foi o momento mais desafiante que viveste nos últimos cinco anos?',"url":"images/momentomaisdesafiante.png",'category':'P'},
  {'card':'Qual foi o momento + triste que viveste nos últimos 3 meses?',"url":"images/momentomaistriste.png",'category':'P'},
  {'card':'?',"url":"images/Surprise.png"},
  {'card':'O que perguntarias a Deus?',"url":"images/perguntaadeus.png",'category':'P'},
  {'card':'Qual é a pergunta que gostavas que te fizessem?',"url":"images/perguntatefizessem.png",'category':'P'},
  {'card':'Conta ao grupo algo que gostarias de realizar nos próximos 2 anos.',"url":"images/realizarproximosdoisanos.png",'category':'P'},
  {'card':'Conta uma situação marcante que viveste com uma pessoa deste grupo.',"url":"images/situacaomarcante.png",'category':'P'},
  {'card':'Tens a tua sobrevivência garantida. Em que te ocupas?',"url":"images/sobrevivenciagarantida.png",'category':'P'},
  {'card':'Quais são os teus três maiores valores ?',"url":"images/tresmaioresvalores.png",'category':'P'},
  {'card':'Alguma vez viste a tua vida andar para trás?',"url":"images/vidaandarparatras.png",'category':'P'},
  {'card':'Partilha um momento em que sentiste raiva. Como agiste?',"url":"images/momentoraiva.png",'category':'P'}
];
final cardsD = [
  {'card':'Conta ao grupo por gestos como aprendeste a andar de bicicleta',"url":"images/comoaprendestebicicleta.png",'category':'D'},
  {'card':'Conta ao grupo como chegaste aqui hoje. Depois pede ao grupo para contar esta história contigo',"url":"images/comochegasteaquihoje.png",'category':'D'},
  {'card':'Como é que foi o teu brimeiro beijo?',"url":"images/comoprimeirobeijo.png",'category':'D'},
  {'card':'Convida alguém do grupo para cantar contigo uma canção de que gostes. Podem improvisar instrumentos.',"url":"images/convidacantarcontigo.png",'category':'D'},
  {'card':'Inventa uma dança com sons. Podes envolver mais pessoas do grupo',"url":"images/dancacomsons.png",'category':'D'},
  {'card':'Faz uma dança em que moves 3 partes do corpo em simultâneo',"url":"images/dancatrespartescorpo.png",'category':'D'},
  {'card':'Imita um animal de que gostes sem revelar qual é',"url":"images/imitaanimal.png",'category':'D'},
  {'card':'Qual foi o momento mais divertido que viveste no último ano?',"url":"images/momentomaisdivertidoano.png",'category':'D'},
  {'card':'Qual foi o momento mais divertido que viveste na última semana?',"url":"images/momentomaisdivertidosemana.png",'category':'D'},
  {'card':'?',"url":"images/Surprise.png"},
  {'card':'O que é que te faz corar?',"url":"images/oquetefazcorar.png",'category':'D'}
];